import {
  mysqlTable,
  mysqlEnum,
  serial,
  varchar,
  text,
  timestamp,
  int,
  decimal,
  boolean,
  bigint,
} from "drizzle-orm/mysql-core";

// ── 1. Auth (auto-generated by backend-building skill) ──
export const users = mysqlTable("users", {
  id: serial("id").primaryKey(),
  unionId: varchar("unionId", { length: 255 }).notNull().unique(),
  name: varchar("name", { length: 255 }),
  email: varchar("email", { length: 320 }),
  avatar: text("avatar"),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().notNull().$onUpdate(() => new Date()),
  lastSignInAt: timestamp("lastSignInAt").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

// ── 2. Restaurant Profile ──
export const restaurants = mysqlTable("restaurants", {
  id: serial("id").primaryKey(),
  nameEn: varchar("name_en", { length: 100 }).notNull(),
  nameAr: varchar("name_ar", { length: 100 }).notNull(),
  city: varchar("city", { length: 50 }).notNull(),
  district: varchar("district", { length: 50 }).notNull(),
  phone: varchar("phone", { length: 20 }).notNull(),
  email: varchar("email", { length: 100 }).notNull(),
  openTime: varchar("open_time", { length: 10 }).notNull(),
  closeTime: varchar("close_time", { length: 10 }).notNull(),
  taxRate: decimal("tax_rate", { precision: 5, scale: 2 }).notNull().default("15.00"),
  currency: varchar("currency", { length: 10 }).notNull().default("SAR"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow().$onUpdate(() => new Date()),
});

export const branches = mysqlTable("branches", {
  id: serial("id").primaryKey(),
  restaurantId: bigint("restaurant_id", { mode: "number", unsigned: true }).references(() => restaurants.id),
  nameEn: varchar("name_en", { length: 100 }).notNull(),
  nameAr: varchar("name_ar", { length: 100 }).notNull(),
  address: varchar("address", { length: 255 }),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
});

export const deliveryAreas = mysqlTable("delivery_areas", {
  id: serial("id").primaryKey(),
  nameEn: varchar("name_en", { length: 50 }).notNull(),
  nameAr: varchar("name_ar", { length: 50 }).notNull(),
  fee: decimal("fee", { precision: 10, scale: 2 }).notNull(),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
});

// ── 3. Menu Management ──
export const categories = mysqlTable("categories", {
  id: serial("id").primaryKey(),
  code: varchar("code", { length: 10 }).notNull().unique(),
  nameEn: varchar("name_en", { length: 50 }).notNull(),
  nameAr: varchar("name_ar", { length: 50 }).notNull(),
  sortOrder: int("sort_order").default(0),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
});

export const products = mysqlTable("products", {
  id: serial("id").primaryKey(),
  code: varchar("code", { length: 10 }).notNull().unique(),
  categoryId: bigint("category_id", { mode: "number", unsigned: true }).references(() => categories.id),
  nameEn: varchar("name_en", { length: 100 }).notNull(),
  nameAr: varchar("name_ar", { length: 100 }).notNull(),
  descriptionEn: varchar("description_en", { length: 255 }),
  descriptionAr: varchar("description_ar", { length: 255 }),
  basePrice: decimal("base_price", { precision: 10, scale: 2 }).notNull(),
  imageUrl: varchar("image_url", { length: 255 }),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow().$onUpdate(() => new Date()),
});

export const productOptions = mysqlTable("product_options", {
  id: serial("id").primaryKey(),
  nameEn: varchar("name_en", { length: 50 }).notNull(),
  nameAr: varchar("name_ar", { length: 50 }).notNull(),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
});

export const productOptionValues = mysqlTable("product_option_values", {
  id: serial("id").primaryKey(),
  optionId: bigint("option_id", { mode: "number", unsigned: true }).references(() => productOptions.id),
  nameEn: varchar("name_en", { length: 50 }).notNull(),
  nameAr: varchar("name_ar", { length: 50 }).notNull(),
  priceAdjustment: decimal("price_adjustment", { precision: 10, scale: 2 }).default("0.00"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const productOptionMappings = mysqlTable("product_option_mappings", {
  id: serial("id").primaryKey(),
  productId: bigint("product_id", { mode: "number", unsigned: true }).references(() => products.id),
  optionId: bigint("option_id", { mode: "number", unsigned: true }).references(() => productOptions.id),
  createdAt: timestamp("created_at").defaultNow(),
});

export const additions = mysqlTable("additions", {
  id: serial("id").primaryKey(),
  nameEn: varchar("name_en", { length: 50 }).notNull(),
  nameAr: varchar("name_ar", { length: 50 }).notNull(),
  price: decimal("price", { precision: 10, scale: 2 }).notNull(),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
});

export const productAdditionMappings = mysqlTable("product_addition_mappings", {
  id: serial("id").primaryKey(),
  productId: bigint("product_id", { mode: "number", unsigned: true }).references(() => products.id),
  additionId: bigint("addition_id", { mode: "number", unsigned: true }).references(() => additions.id),
  createdAt: timestamp("created_at").defaultNow(),
});

export const offers = mysqlTable("offers", {
  id: serial("id").primaryKey(),
  code: varchar("code", { length: 30 }).notNull().unique(),
  nameEn: varchar("name_en", { length: 100 }).notNull(),
  nameAr: varchar("name_ar", { length: 100 }).notNull(),
  descriptionEn: varchar("description_en", { length: 255 }),
  descriptionAr: varchar("description_ar", { length: 255 }),
  price: decimal("price", { precision: 10, scale: 2 }).notNull(),
  imageUrl: varchar("image_url", { length: 255 }),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
});

// ── 4. Order Management ──
export const orders = mysqlTable("orders", {
  id: serial("id").primaryKey(),
  orderNumber: varchar("order_number", { length: 20 }).notNull().unique(),
  customerName: varchar("customer_name", { length: 100 }).notNull(),
  customerPhone: varchar("customer_phone", { length: 20 }).notNull(),
  customerEmail: varchar("customer_email", { length: 100 }),
  customerAddress: varchar("customer_address", { length: 255 }),
  deliveryAreaId: bigint("delivery_area_id", { mode: "number", unsigned: true }).references(() => deliveryAreas.id),
  orderType: mysqlEnum("order_type", ["delivery", "pickup", "dine_in"]).notNull(),
  tableNumber: varchar("table_number", { length: 10 }),
  paymentMethod: mysqlEnum("payment_method", ["mada", "apple_pay", "stc_pay", "visa", "cash"]).notNull(),
  subtotal: decimal("subtotal", { precision: 10, scale: 2 }).notNull(),
  taxAmount: decimal("tax_amount", { precision: 10, scale: 2 }).notNull(),
  deliveryFee: decimal("delivery_fee", { precision: 10, scale: 2 }).default("0.00"),
  discountAmount: decimal("discount_amount", { precision: 10, scale: 2 }).default("0.00"),
  total: decimal("total", { precision: 10, scale: 2 }).notNull(),
  status: mysqlEnum("status", [
    "new", "accepted", "preparing", "ready",
    "out_for_delivery", "driver_assigned", "on_the_way",
    "delivered", "completed", "cancelled"
  ]).notNull().default("new"),
  notes: varchar("notes", { length: 500 }),
  couponCode: varchar("coupon_code", { length: 50 }),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow().$onUpdate(() => new Date()),
});

export const orderItems = mysqlTable("order_items", {
  id: serial("id").primaryKey(),
  orderId: bigint("order_id", { mode: "number", unsigned: true }).references(() => orders.id),
  itemType: mysqlEnum("item_type", ["product", "offer"]).notNull().default("product"),
  code: varchar("code", { length: 30 }),
  productId: bigint("product_id", { mode: "number", unsigned: true }).references(() => products.id),
  offerId: bigint("offer_id", { mode: "number", unsigned: true }).references(() => offers.id),
  productNameEn: varchar("product_name_en", { length: 100 }).notNull(),
  productNameAr: varchar("product_name_ar", { length: 100 }).notNull(),
  quantity: int("quantity").notNull().default(1),
  unitPrice: decimal("unit_price", { precision: 10, scale: 2 }).notNull(),
  totalPrice: decimal("total_price", { precision: 10, scale: 2 }).notNull(),
  selectedOptions: varchar("selected_options", { length: 500 }),
  selectedAdditions: varchar("selected_additions", { length: 500 }),
  notes: varchar("notes", { length: 255 }),
  createdAt: timestamp("created_at").defaultNow(),
});

export const orderStatusHistory = mysqlTable("order_status_history", {
  id: serial("id").primaryKey(),
  orderId: bigint("order_id", { mode: "number", unsigned: true }).references(() => orders.id),
  status: varchar("status", { length: 50 }).notNull(),
  notes: varchar("notes", { length: 255 }),
  createdBy: varchar("created_by", { length: 100 }),
  createdAt: timestamp("created_at").defaultNow(),
});

// ── 5. POS & Tables ──
export const tables = mysqlTable("tables", {
  id: serial("id").primaryKey(),
  tableNumber: varchar("table_number", { length: 10 }).notNull().unique(),
  capacity: int("capacity").notNull(),
  status: mysqlEnum("status", ["available", "occupied", "reserved"]).default("available"),
  currentOrderId: bigint("current_order_id", { mode: "number", unsigned: true }),
  createdAt: timestamp("created_at").defaultNow(),
});

export const shifts = mysqlTable("shifts", {
  id: serial("id").primaryKey(),
  cashierName: varchar("cashier_name", { length: 100 }).notNull(),
  startedAt: timestamp("started_at").defaultNow(),
  endedAt: timestamp("ended_at"),
  openingAmount: decimal("opening_amount", { precision: 10, scale: 2 }).notNull(),
  closingAmount: decimal("closing_amount", { precision: 10, scale: 2 }),
  status: mysqlEnum("status", ["open", "closed"]).default("open"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const invoices = mysqlTable("invoices", {
  id: serial("id").primaryKey(),
  invoiceNumber: varchar("invoice_number", { length: 20 }).notNull().unique(),
  orderId: bigint("order_id", { mode: "number", unsigned: true }).references(() => orders.id),
  shiftId: bigint("shift_id", { mode: "number", unsigned: true }).references(() => shifts.id),
  amount: decimal("amount", { precision: 10, scale: 2 }).notNull(),
  taxAmount: decimal("tax_amount", { precision: 10, scale: 2 }).notNull(),
  total: decimal("total", { precision: 10, scale: 2 }).notNull(),
  paymentMethod: varchar("payment_method", { length: 20 }).notNull(),
  isRefunded: boolean("is_refunded").default(false),
  createdAt: timestamp("created_at").defaultNow(),
});

// ── 6. Inventory Management ──
export const inventoryItems = mysqlTable("inventory_items", {
  id: serial("id").primaryKey(),
  code: varchar("code", { length: 10 }).notNull().unique(),
  nameEn: varchar("name_en", { length: 100 }).notNull(),
  nameAr: varchar("name_ar", { length: 100 }).notNull(),
  currentStock: decimal("current_stock", { precision: 10, scale: 2 }).notNull().default("0.00"),
  unit: varchar("unit", { length: 20 }).notNull(),
  minThreshold: decimal("min_threshold", { precision: 10, scale: 2 }).default("10.00"),
  costPerUnit: decimal("cost_per_unit", { precision: 10, scale: 2 }),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow().$onUpdate(() => new Date()),
});

export const recipes = mysqlTable("recipes", {
  id: serial("id").primaryKey(),
  productId: bigint("product_id", { mode: "number", unsigned: true }).references(() => products.id),
  inventoryItemId: bigint("inventory_item_id", { mode: "number", unsigned: true }).references(() => inventoryItems.id),
  quantityRequired: decimal("quantity_required", { precision: 10, scale: 2 }).notNull(),
  createdAt: timestamp("created_at").defaultNow(),
});

export const stockMovements = mysqlTable("stock_movements", {
  id: serial("id").primaryKey(),
  inventoryItemId: bigint("inventory_item_id", { mode: "number", unsigned: true }).references(() => inventoryItems.id),
  movementType: mysqlEnum("movement_type", ["in", "out", "adjustment", "waste"]).notNull(),
  quantity: decimal("quantity", { precision: 10, scale: 2 }).notNull(),
  reason: varchar("reason", { length: 255 }),
  referenceType: varchar("reference_type", { length: 50 }),
  referenceId: bigint("reference_id", { mode: "number", unsigned: true }),
  createdBy: varchar("created_by", { length: 100 }),
  createdAt: timestamp("created_at").defaultNow(),
});

// ── 7. Procurement ──
export const suppliers = mysqlTable("suppliers", {
  id: serial("id").primaryKey(),
  name: varchar("name", { length: 100 }).notNull(),
  contactPerson: varchar("contact_person", { length: 100 }),
  phone: varchar("phone", { length: 20 }),
  email: varchar("email", { length: 100 }),
  address: varchar("address", { length: 255 }),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
});

export const purchaseOrders = mysqlTable("purchase_orders", {
  id: serial("id").primaryKey(),
  poNumber: varchar("po_number", { length: 20 }).notNull().unique(),
  supplierId: bigint("supplier_id", { mode: "number", unsigned: true }).references(() => suppliers.id),
  status: mysqlEnum("status", ["draft", "sent", "partial", "received", "cancelled"]).default("draft"),
  total: decimal("total", { precision: 10, scale: 2 }).notNull(),
  notes: varchar("notes", { length: 500 }),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow().$onUpdate(() => new Date()),
});

export const purchaseOrderItems = mysqlTable("purchase_order_items", {
  id: serial("id").primaryKey(),
  poId: bigint("po_id", { mode: "number", unsigned: true }).references(() => purchaseOrders.id),
  inventoryItemId: bigint("inventory_item_id", { mode: "number", unsigned: true }).references(() => inventoryItems.id),
  quantity: decimal("quantity", { precision: 10, scale: 2 }).notNull(),
  unitPrice: decimal("unit_price", { precision: 10, scale: 2 }).notNull(),
  total: decimal("total", { precision: 10, scale: 2 }).notNull(),
  receivedQuantity: decimal("received_quantity", { precision: 10, scale: 2 }).default("0.00"),
  createdAt: timestamp("created_at").defaultNow(),
});

// ── 8. CRM ──
export const customers = mysqlTable("customers", {
  id: serial("id").primaryKey(),
  code: varchar("code", { length: 10 }).notNull().unique(),
  name: varchar("name", { length: 100 }).notNull(),
  phone: varchar("phone", { length: 20 }).notNull(),
  email: varchar("email", { length: 100 }),
  address: varchar("address", { length: 255 }),
  loyaltyPoints: int("loyalty_points").default(0),
  totalOrders: int("total_orders").default(0),
  totalSpent: decimal("total_spent", { precision: 10, scale: 2 }).default("0.00"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow().$onUpdate(() => new Date()),
});

export const coupons = mysqlTable("coupons", {
  id: serial("id").primaryKey(),
  code: varchar("code", { length: 50 }).notNull().unique(),
  discountType: mysqlEnum("discount_type", ["percentage", "fixed"]).notNull(),
  discountValue: decimal("discount_value", { precision: 10, scale: 2 }).notNull(),
  minOrderAmount: decimal("min_order_amount", { precision: 10, scale: 2 }).default("0.00"),
  maxUsage: int("max_usage"),
  usedCount: int("used_count").default(0),
  startDate: timestamp("start_date"),
  endDate: timestamp("end_date"),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
});

export const reviews = mysqlTable("reviews", {
  id: serial("id").primaryKey(),
  customerId: bigint("customer_id", { mode: "number", unsigned: true }).references(() => customers.id),
  orderId: bigint("order_id", { mode: "number", unsigned: true }).references(() => orders.id),
  rating: int("rating").notNull(),
  comment: varchar("comment", { length: 500 }),
  isVisible: boolean("is_visible").default(true),
  createdAt: timestamp("created_at").defaultNow(),
});

export const loyaltyRewards = mysqlTable("loyalty_rewards", {
  id: serial("id").primaryKey(),
  nameEn: varchar("name_en", { length: 100 }).notNull(),
  nameAr: varchar("name_ar", { length: 100 }).notNull(),
  pointsRequired: int("points_required").notNull(),
  rewardType: mysqlEnum("reward_type", ["discount", "free_item"]).notNull(),
  rewardValue: decimal("reward_value", { precision: 10, scale: 2 }),
  freeProductId: bigint("free_product_id", { mode: "number", unsigned: true }).references(() => products.id),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
});

// ── 9. Marketing ──
export const campaigns = mysqlTable("campaigns", {
  id: serial("id").primaryKey(),
  nameEn: varchar("name_en", { length: 100 }).notNull(),
  nameAr: varchar("name_ar", { length: 100 }).notNull(),
  campaignType: mysqlEnum("campaign_type", ["weekend_offer", "pizza_night", "free_delivery", "custom"]).notNull(),
  description: varchar("description", { length: 500 }),
  startDate: timestamp("start_date").notNull(),
  endDate: timestamp("end_date").notNull(),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
});

export const banners = mysqlTable("banners", {
  id: serial("id").primaryKey(),
  titleEn: varchar("title_en", { length: 100 }).notNull(),
  titleAr: varchar("title_ar", { length: 100 }).notNull(),
  imageUrl: varchar("image_url", { length: 255 }).notNull(),
  linkUrl: varchar("link_url", { length: 255 }),
  displayOrder: int("display_order").default(0),
  startDate: timestamp("start_date"),
  endDate: timestamp("end_date"),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
});

// ── 10. System Users & Activity Logs ──
export const systemUsers = mysqlTable("system_users", {
  id: serial("id").primaryKey(),
  fullName: varchar("full_name", { length: 100 }).notNull(),
  email: varchar("email", { length: 100 }).notNull().unique(),
  phone: varchar("phone", { length: 20 }),
  role: mysqlEnum("role", ["admin", "branch_manager", "cashier", "kitchen", "inventory", "marketing"]).notNull(),
  isActive: boolean("is_active").default(true),
  lastLogin: timestamp("last_login"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow().$onUpdate(() => new Date()),
});

export const activityLogs = mysqlTable("activity_logs", {
  id: serial("id").primaryKey(),
  userId: bigint("user_id", { mode: "number", unsigned: true }).references(() => systemUsers.id),
  userName: varchar("user_name", { length: 100 }),
  action: varchar("action", { length: 100 }).notNull(),
  entityType: varchar("entity_type", { length: 50 }),
  entityId: varchar("entity_id", { length: 20 }),
  details: varchar("details", { length: 500 }),
  ipAddress: varchar("ip_address", { length: 50 }),
  createdAt: timestamp("created_at").defaultNow(),
});

// ── 11. Notifications & Settings ──
export const notifications = mysqlTable("notifications", {
  id: serial("id").primaryKey(),
  type: mysqlEnum("type", [
    "new_order", "order_accepted", "order_ready",
    "order_cancelled", "low_stock", "general"
  ]).notNull(),
  titleEn: varchar("title_en", { length: 100 }).notNull(),
  titleAr: varchar("title_ar", { length: 100 }).notNull(),
  messageEn: varchar("message_en", { length: 255 }),
  messageAr: varchar("message_ar", { length: 255 }),
  isRead: boolean("is_read").default(false),
  relatedEntityType: varchar("related_entity_type", { length: 50 }),
  relatedEntityId: varchar("related_entity_id", { length: 20 }),
  createdAt: timestamp("created_at").defaultNow(),
});

export const settings = mysqlTable("settings", {
  id: serial("id").primaryKey(),
  key: varchar("key", { length: 100 }).notNull().unique(),
  value: varchar("value", { length: 500 }),
  group: varchar("group", { length: 50 }).notNull(),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow().$onUpdate(() => new Date()),
});

// ── Export types ──
export type Restaurant = typeof restaurants.$inferSelect;
export type Category = typeof categories.$inferSelect;
export type Product = typeof products.$inferSelect;
export type Addition = typeof additions.$inferSelect;
export type Order = typeof orders.$inferSelect;
export type OrderItem = typeof orderItems.$inferSelect;
export type Customer = typeof customers.$inferSelect;
export type Coupon = typeof coupons.$inferSelect;
export type InventoryItem = typeof inventoryItems.$inferSelect;
export type Supplier = typeof suppliers.$inferSelect;
export type PurchaseOrder = typeof purchaseOrders.$inferSelect;
export type Table = typeof tables.$inferSelect;
export type Campaign = typeof campaigns.$inferSelect;
export type Banner = typeof banners.$inferSelect;
export type SystemUser = typeof systemUsers.$inferSelect;
export type Notification = typeof notifications.$inferSelect;
export type Setting = typeof settings.$inferSelect;
export type DeliveryArea = typeof deliveryAreas.$inferSelect;
